kind: Service
apiVersion: v1
metadata:
  name: microserviceTest
  labels:
    app: microserviceTest
spec:
  type: NodePort
  selector:
    app: microserviceTest
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: microserviceTest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microserviceTest
  template:
    metadata:
      labels:
        app: microserviceTest
        version: v1
    spec:
      containers:
      - name: microserviceTest
        image: microserviceTest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
